version: 0.0 
os: linux 
files:
  - source: /
    destination: /var/www/html/
hooks:  
BeforeInstall:    
  – location: script/beforecicd.sh      
  runas: root 

AfterInstall:    
  – location: script/aftercicd.sh      
  runas: root